// SPDX-License-Identifier: (LGPL-2.1 OR BSD-2-Clause)
//
// THIS FILE IS AUTOGENERATED BY CARGO-LIBBPF-GEN!

pub use self::imp::*;

#[allow(dead_code)]
#[allow(non_snake_case)]
#[allow(non_camel_case_types)]
#[allow(clippy::absolute_paths)]
#[allow(clippy::upper_case_acronyms)]
#[allow(clippy::zero_repeat_side_effects)]
#[warn(single_use_lifetimes)]
mod imp {
    #[allow(unused_imports)]
    use super::*;
    use libbpf_rs::libbpf_sys;
    use libbpf_rs::skel::OpenSkel;
    use libbpf_rs::skel::Skel;
    use libbpf_rs::skel::SkelBuilder;
    use libbpf_rs::AsRawLibbpf as _;
    use libbpf_rs::MapCore as _;
    fn build_skel_config(
    ) -> libbpf_rs::Result<libbpf_rs::__internal_skel::ObjectSkeletonConfig<'static>> {
        let mut builder = libbpf_rs::__internal_skel::ObjectSkeletonConfigBuilder::new(DATA);
        builder
            .name("port_mapper_bpf")
            .map("solver_socket", false)
            .map("port_map.rodata", true)
            .prog("proxy_challenge");
        builder.build()
    }
    pub struct OpenPortMapperMaps<'obj> {
        pub solver_socket: libbpf_rs::OpenMapMut<'obj>,
        pub rodata: libbpf_rs::OpenMapMut<'obj>,
        pub rodata_data: &'obj mut types::rodata,
        _phantom: std::marker::PhantomData<&'obj ()>,
    }

    impl<'obj> OpenPortMapperMaps<'obj> {
        #[allow(unused_variables)]
        unsafe fn new(
            config: &libbpf_rs::__internal_skel::ObjectSkeletonConfig<'_>,
            object: &mut libbpf_rs::OpenObject,
        ) -> libbpf_rs::Result<Self> {
            let mut solver_socket = None;
            let mut rodata = None;
            let object = unsafe {
                std::mem::transmute::<&mut libbpf_rs::OpenObject, &'obj mut libbpf_rs::OpenObject>(
                    object,
                )
            };
            #[allow(clippy::never_loop)]
            for map in object.maps_mut() {
                let name = map.name().to_str().ok_or_else(|| {
                    libbpf_rs::Error::from(std::io::Error::new(
                        std::io::ErrorKind::InvalidData,
                        "map has invalid name",
                    ))
                })?;
                #[allow(clippy::match_single_binding)]
                match name {
                    "solver_socket" => solver_socket = Some(map),
                    "port_map.rodata" => rodata = Some(map),
                    _ => panic!("encountered unexpected map: `{name}`"),
                }
            }

            let slf = Self {
                solver_socket: solver_socket.expect("map `solver_socket` not present"),
                rodata: rodata.expect("map `rodata` not present"),
                rodata_data: unsafe {
                    config
                        .map_mmap_ptr(1)
                        .expect("BPF map `rodata` does not have mmap pointer")
                        .cast::<types::rodata>()
                        .as_mut()
                        .expect("BPF map `rodata` mmap pointer is NULL")
                },
                _phantom: std::marker::PhantomData,
            };
            Ok(slf)
        }
    }
    pub struct PortMapperMaps<'obj> {
        pub solver_socket: libbpf_rs::MapMut<'obj>,
        pub rodata: libbpf_rs::MapMut<'obj>,
        pub rodata_data: &'obj types::rodata,
        _phantom: std::marker::PhantomData<&'obj ()>,
    }

    impl<'obj> PortMapperMaps<'obj> {
        #[allow(unused_variables)]
        unsafe fn new(
            config: &libbpf_rs::__internal_skel::ObjectSkeletonConfig<'_>,
            object: &mut libbpf_rs::Object,
        ) -> libbpf_rs::Result<Self> {
            let mut solver_socket = None;
            let mut rodata = None;
            let object = unsafe {
                std::mem::transmute::<&mut libbpf_rs::Object, &'obj mut libbpf_rs::Object>(object)
            };
            #[allow(clippy::never_loop)]
            for map in object.maps_mut() {
                let name = map.name().to_str().ok_or_else(|| {
                    libbpf_rs::Error::from(std::io::Error::new(
                        std::io::ErrorKind::InvalidData,
                        "map has invalid name",
                    ))
                })?;
                #[allow(clippy::match_single_binding)]
                match name {
                    "solver_socket" => solver_socket = Some(map),
                    "port_map.rodata" => rodata = Some(map),
                    _ => panic!("encountered unexpected map: `{name}`"),
                }
            }

            let slf = Self {
                solver_socket: solver_socket.expect("map `solver_socket` not present"),
                rodata: rodata.expect("map `rodata` not present"),
                rodata_data: unsafe {
                    config
                        .map_mmap_ptr(1)
                        .expect("BPF map `rodata` does not have mmap pointer")
                        .cast::<types::rodata>()
                        .as_ref()
                        .expect("BPF map `rodata` mmap pointer is NULL")
                },
                _phantom: std::marker::PhantomData,
            };
            Ok(slf)
        }
    }
    pub struct OpenPortMapperProgs<'obj> {
        pub proxy_challenge: libbpf_rs::OpenProgramMut<'obj>,
        _phantom: std::marker::PhantomData<&'obj ()>,
    }

    impl<'obj> OpenPortMapperProgs<'obj> {
        unsafe fn new(object: &mut libbpf_rs::OpenObject) -> libbpf_rs::Result<Self> {
            let mut proxy_challenge = None;
            let object = unsafe {
                std::mem::transmute::<&mut libbpf_rs::OpenObject, &'obj mut libbpf_rs::OpenObject>(
                    object,
                )
            };
            for prog in object.progs_mut() {
                let name = prog.name().to_str().ok_or_else(|| {
                    libbpf_rs::Error::from(std::io::Error::new(
                        std::io::ErrorKind::InvalidData,
                        "prog has invalid name",
                    ))
                })?;
                match name {
                    "proxy_challenge" => proxy_challenge = Some(prog),
                    _ => panic!("encountered unexpected prog: `{name}`"),
                }
            }

            let slf = Self {
                proxy_challenge: proxy_challenge.expect("prog `proxy_challenge` not present"),
                _phantom: std::marker::PhantomData,
            };
            Ok(slf)
        }
    }
    pub struct PortMapperProgs<'obj> {
        pub proxy_challenge: libbpf_rs::ProgramMut<'obj>,
        _phantom: std::marker::PhantomData<&'obj ()>,
    }

    impl<'obj> PortMapperProgs<'obj> {
        #[allow(unused_variables)]
        fn new(open_progs: OpenPortMapperProgs<'obj>) -> Self {
            Self {
                proxy_challenge: unsafe {
                    libbpf_rs::ProgramMut::new_mut(
                        open_progs.proxy_challenge.as_libbpf_object().as_mut(),
                    )
                },
                _phantom: std::marker::PhantomData,
            }
        }
    }
    struct OwnedRef<'obj, O> {
        object: Option<&'obj mut std::mem::MaybeUninit<O>>,
    }

    impl<'obj, O> OwnedRef<'obj, O> {
        /// # Safety
        /// The object has to be initialized.
        unsafe fn new(object: &'obj mut std::mem::MaybeUninit<O>) -> Self {
            Self {
                object: Some(object),
            }
        }

        fn as_ref(&self) -> &O {
            // SAFETY: As per the contract during construction, the
            //         object has to be initialized.
            unsafe { self.object.as_ref().unwrap().assume_init_ref() }
        }

        fn as_mut(&mut self) -> &mut O {
            // SAFETY: As per the contract during construction, the
            //         object has to be initialized.
            unsafe { self.object.as_mut().unwrap().assume_init_mut() }
        }

        fn take(mut self) -> &'obj mut std::mem::MaybeUninit<O> {
            self.object.take().unwrap()
        }
    }

    impl<O> Drop for OwnedRef<'_, O> {
        fn drop(&mut self) {
            if let Some(object) = &mut self.object {
                unsafe { object.assume_init_drop() }
            }
        }
    }

    #[derive(Default)]
    pub struct PortMapperSkelBuilder {
        pub obj_builder: libbpf_rs::ObjectBuilder,
    }

    impl<'obj> PortMapperSkelBuilder {
        fn open_opts_impl(
            self,
            open_opts: *const libbpf_sys::bpf_object_open_opts,
            object: &'obj mut std::mem::MaybeUninit<libbpf_rs::OpenObject>,
        ) -> libbpf_rs::Result<OpenPortMapperSkel<'obj>> {
            let skel_config = build_skel_config()?;
            let skel_ptr = skel_config.as_libbpf_object();

            let ret =
                unsafe { libbpf_sys::bpf_object__open_skeleton(skel_ptr.as_ptr(), open_opts) };
            if ret != 0 {
                return Err(libbpf_rs::Error::from_raw_os_error(-ret));
            }

            // SAFETY: `skel_ptr` points to a valid object after the
            //         open call.
            let obj_ptr = unsafe { *skel_ptr.as_ref().obj };
            // SANITY: `bpf_object__open_skeleton` should have
            //         allocated the object.
            let obj_ptr = std::ptr::NonNull::new(obj_ptr).unwrap();
            // SAFETY: `obj_ptr` points to an opened object after
            //         skeleton open.
            let obj = unsafe { libbpf_rs::OpenObject::from_ptr(obj_ptr) };
            let _obj = object.write(obj);
            // SAFETY: We just wrote initialized data to `object`.
            let mut obj_ref = unsafe { OwnedRef::new(object) };

            #[allow(unused_mut)]
            let mut skel = OpenPortMapperSkel {
                maps: unsafe { OpenPortMapperMaps::new(&skel_config, obj_ref.as_mut())? },
                progs: unsafe { OpenPortMapperProgs::new(obj_ref.as_mut())? },
                obj: obj_ref,
                // SAFETY: Our `struct_ops` type contains only pointers,
                //         which are allowed to be NULL.
                // TODO: Generate and use a `Default` representation
                //       instead, to cut down on unsafe code.
                struct_ops: unsafe { std::mem::zeroed() },
                skel_config,
            };

            Ok(skel)
        }
    }

    impl<'obj> SkelBuilder<'obj> for PortMapperSkelBuilder {
        type Output = OpenPortMapperSkel<'obj>;
        fn open(
            self,
            object: &'obj mut std::mem::MaybeUninit<libbpf_rs::OpenObject>,
        ) -> libbpf_rs::Result<OpenPortMapperSkel<'obj>> {
            self.open_opts_impl(std::ptr::null(), object)
        }

        fn open_opts(
            self,
            open_opts: libbpf_sys::bpf_object_open_opts,
            object: &'obj mut std::mem::MaybeUninit<libbpf_rs::OpenObject>,
        ) -> libbpf_rs::Result<OpenPortMapperSkel<'obj>> {
            self.open_opts_impl(&open_opts, object)
        }

        fn object_builder(&self) -> &libbpf_rs::ObjectBuilder {
            &self.obj_builder
        }
        fn object_builder_mut(&mut self) -> &mut libbpf_rs::ObjectBuilder {
            &mut self.obj_builder
        }
    }

    #[derive(Debug, Clone)]
    #[repr(C)]
    pub struct StructOps {}

    impl StructOps {}
    pub mod types {
        #[allow(unused_imports)]
        use super::*;
        #[derive(Debug, Copy, Clone)]
        #[repr(C)]
        pub struct __anon_1 {
            pub r#type: *mut [i32; 15],
            pub max_entries: *mut [i32; 2],
            pub key: *mut u32,
            pub value: *mut u32,
        }
        impl Default for __anon_1 {
            fn default() -> Self {
                Self {
                    r#type: std::ptr::null_mut(),
                    max_entries: std::ptr::null_mut(),
                    key: std::ptr::null_mut(),
                    value: std::ptr::null_mut(),
                }
            }
        }
        #[derive(Debug, Default, Copy, Clone)]
        #[repr(C)]
        pub struct bpf_sk_lookup {
            pub __anon_2: __anon_2,
            pub family: u32,
            pub protocol: u32,
            pub remote_ip4: u32,
            pub remote_ip6: [u32; 4],
            pub remote_port: u16,
            pub local_ip4: u32,
            pub local_ip6: [u32; 4],
            pub local_port: u32,
            pub ingress_ifindex: u32,
            pub __pad_68: [u8; 4],
        }
        #[derive(Copy, Clone)]
        #[repr(C)]
        pub union __anon_2 {
            pub __anon_3: __anon_3,
            pub cookie: u64,
        }
        impl std::fmt::Debug for __anon_2 {
            fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
                write!(f, "(???)")
            }
        }
        impl Default for __anon_2 {
            fn default() -> Self {
                Self {
                    __anon_3: __anon_3::default(),
                }
            }
        }
        #[derive(Copy, Clone)]
        #[repr(C)]
        pub union __anon_3 {
            pub sk: *mut std::ffi::c_void,
        }
        impl std::fmt::Debug for __anon_3 {
            fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
                write!(f, "(???)")
            }
        }
        impl Default for __anon_3 {
            fn default() -> Self {
                Self {
                    sk: std::ptr::null_mut(),
                }
            }
        }
        #[derive(Debug, Copy, Clone)]
        #[repr(C)]
        pub struct license {
            pub LICENSE: [i8; 12],
        }
        #[derive(Debug, Copy, Clone)]
        #[repr(C)]
        pub struct rodata {
            pub CHALLENGE_PORT: u32,
        }
        #[derive(Debug, Copy, Clone)]
        #[repr(C)]
        pub struct maps {
            pub solver_socket: __anon_1,
        }
    }
    pub struct OpenPortMapperSkel<'obj> {
        obj: OwnedRef<'obj, libbpf_rs::OpenObject>,
        pub maps: OpenPortMapperMaps<'obj>,
        pub progs: OpenPortMapperProgs<'obj>,
        pub struct_ops: StructOps,
        skel_config: libbpf_rs::__internal_skel::ObjectSkeletonConfig<'obj>,
    }

    impl<'obj> OpenSkel<'obj> for OpenPortMapperSkel<'obj> {
        type Output = PortMapperSkel<'obj>;
        fn load(self) -> libbpf_rs::Result<PortMapperSkel<'obj>> {
            let skel_ptr = self.skel_config.as_libbpf_object().as_ptr();

            let ret = unsafe { libbpf_sys::bpf_object__load_skeleton(skel_ptr) };
            if ret != 0 {
                return Err(libbpf_rs::Error::from_raw_os_error(-ret));
            }

            let obj_ref = self.obj.take();
            let open_obj = std::mem::replace(obj_ref, std::mem::MaybeUninit::uninit());
            // SAFETY: `open_obj` is guaranteed to be properly
            //         initialized as it came from an `OwnedRef`.
            let obj_ptr = unsafe { open_obj.assume_init().take_ptr() };
            // SAFETY: `obj_ptr` points to a loaded object after
            //         skeleton load.
            let obj = unsafe { libbpf_rs::Object::from_ptr(obj_ptr) };
            // SAFETY: `OpenObject` and `Object` are guaranteed to
            //         have the same memory layout.
            let obj_ref = unsafe {
                std::mem::transmute::<
                    &'obj mut std::mem::MaybeUninit<libbpf_rs::OpenObject>,
                    &'obj mut std::mem::MaybeUninit<libbpf_rs::Object>,
                >(obj_ref)
            };
            let _obj = obj_ref.write(obj);
            // SAFETY: We just wrote initialized data to `obj_ref`.
            let mut obj_ref = unsafe { OwnedRef::new(obj_ref) };

            Ok(PortMapperSkel {
                maps: unsafe { PortMapperMaps::new(&self.skel_config, obj_ref.as_mut())? },
                progs: PortMapperProgs::new(self.progs),
                obj: obj_ref,
                struct_ops: self.struct_ops,
                skel_config: self.skel_config,
                links: PortMapperLinks::default(),
            })
        }

        fn open_object(&self) -> &libbpf_rs::OpenObject {
            self.obj.as_ref()
        }

        fn open_object_mut(&mut self) -> &mut libbpf_rs::OpenObject {
            self.obj.as_mut()
        }
    }
    #[derive(Default)]
    pub struct PortMapperLinks {
        pub proxy_challenge: Option<libbpf_rs::Link>,
    }
    pub struct PortMapperSkel<'obj> {
        obj: OwnedRef<'obj, libbpf_rs::Object>,
        pub maps: PortMapperMaps<'obj>,
        pub progs: PortMapperProgs<'obj>,
        struct_ops: StructOps,
        skel_config: libbpf_rs::__internal_skel::ObjectSkeletonConfig<'obj>,
        pub links: PortMapperLinks,
    }

    unsafe impl Send for PortMapperSkel<'_> {}
    unsafe impl Sync for PortMapperSkel<'_> {}

    impl<'obj> Skel<'obj> for PortMapperSkel<'obj> {
        fn object(&self) -> &libbpf_rs::Object {
            self.obj.as_ref()
        }

        fn object_mut(&mut self) -> &mut libbpf_rs::Object {
            self.obj.as_mut()
        }
        fn attach(&mut self) -> libbpf_rs::Result<()> {
            let skel_ptr = self.skel_config.as_libbpf_object().as_ptr();
            let ret = unsafe { libbpf_sys::bpf_object__attach_skeleton(skel_ptr) };
            if ret != 0 {
                return Err(libbpf_rs::Error::from_raw_os_error(-ret));
            }

            self.links = PortMapperLinks {
                proxy_challenge: core::ptr::NonNull::new(self.skel_config.prog_link_ptr(0)?)
                    .map(|ptr| unsafe { libbpf_rs::Link::from_ptr(ptr) }),
            };

            Ok(())
        }
    }
    impl PortMapperSkel<'_> {
        pub fn struct_ops_raw(&self) -> *const StructOps {
            &self.struct_ops
        }

        pub fn struct_ops(&self) -> &StructOps {
            &self.struct_ops
        }
    }
    const DATA: &[u8] = &[
        127, 69, 76, 70, 2, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 247, 0, 1, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 176, 11, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 64, 0, 0, 0, 0,
        0, 64, 0, 10, 0, 1, 0, 0, 46, 115, 116, 114, 116, 97, 98, 0, 46, 115, 121, 109, 116, 97,
        98, 0, 115, 107, 95, 108, 111, 111, 107, 117, 112, 0, 108, 105, 99, 101, 110, 115, 101, 0,
        46, 114, 111, 100, 97, 116, 97, 0, 46, 109, 97, 112, 115, 0, 112, 111, 114, 116, 95, 109,
        97, 112, 112, 101, 114, 46, 98, 112, 102, 46, 99, 0, 76, 66, 66, 48, 95, 50, 0, 76, 66, 66,
        48, 95, 49, 48, 0, 76, 66, 66, 48, 95, 54, 0, 76, 66, 66, 48, 95, 56, 0, 112, 114, 111,
        120, 121, 95, 99, 104, 97, 108, 108, 101, 110, 103, 101, 0, 67, 72, 65, 76, 76, 69, 78, 71,
        69, 95, 80, 79, 82, 84, 0, 115, 111, 108, 118, 101, 114, 95, 115, 111, 99, 107, 101, 116,
        0, 76, 73, 67, 69, 78, 83, 69, 0, 46, 114, 101, 108, 115, 107, 95, 108, 111, 111, 107, 117,
        112, 0, 46, 66, 84, 70, 0, 46, 66, 84, 70, 46, 101, 120, 116, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 49, 0, 0, 0, 4, 0, 241,
        255, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3, 0, 3, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 67, 0, 0, 0, 0, 0, 3, 0, 32, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 74, 0, 0, 0, 0, 0, 3, 0, 16, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        82, 0, 0, 0, 0, 0, 3, 0, 120, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 89, 0, 0, 0, 0,
        0, 3, 0, 160, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 96, 0, 0, 0, 18, 0, 3, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 32, 1, 0, 0, 0, 0, 0, 0, 112, 0, 0, 0, 17, 0, 5, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 4, 0, 0, 0, 0, 0, 0, 0, 127, 0, 0, 0, 17, 0, 6, 0, 0, 0, 0, 0, 0, 0, 0, 0, 32, 0, 0, 0,
        0, 0, 0, 0, 141, 0, 0, 0, 17, 0, 4, 0, 0, 0, 0, 0, 0, 0, 0, 0, 12, 0, 0, 0, 0, 0, 0, 0, 97,
        18, 8, 0, 0, 0, 0, 0, 21, 2, 2, 0, 2, 0, 0, 0, 97, 18, 8, 0, 0, 0, 0, 0, 85, 2, 30, 0, 10,
        0, 0, 0, 97, 18, 12, 0, 0, 0, 0, 0, 85, 2, 28, 0, 6, 0, 0, 0, 97, 18, 60, 0, 0, 0, 0, 0,
        24, 3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 97, 51, 0, 0, 0, 0, 0, 0, 93, 50, 23, 0,
        0, 0, 0, 0, 97, 18, 8, 0, 0, 0, 0, 0, 85, 2, 2, 0, 2, 0, 0, 0, 97, 18, 16, 0, 0, 0, 0, 0,
        21, 2, 19, 0, 127, 0, 0, 1, 191, 22, 0, 0, 0, 0, 0, 0, 97, 18, 8, 0, 0, 0, 0, 0, 183, 1, 0,
        0, 1, 0, 0, 0, 85, 2, 1, 0, 2, 0, 0, 0, 183, 1, 0, 0, 0, 0, 0, 0, 99, 26, 252, 255, 0, 0,
        0, 0, 191, 162, 0, 0, 0, 0, 0, 0, 7, 2, 0, 0, 252, 255, 255, 255, 24, 1, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 133, 0, 0, 0, 1, 0, 0, 0, 21, 0, 7, 0, 0, 0, 0, 0, 191, 97, 0, 0,
        0, 0, 0, 0, 191, 2, 0, 0, 0, 0, 0, 0, 183, 3, 0, 0, 0, 0, 0, 0, 191, 6, 0, 0, 0, 0, 0, 0,
        133, 0, 0, 0, 124, 0, 0, 0, 191, 97, 0, 0, 0, 0, 0, 0, 133, 0, 0, 0, 86, 0, 0, 0, 183, 0,
        0, 0, 1, 0, 0, 0, 149, 0, 0, 0, 0, 0, 0, 0, 80, 114, 111, 112, 114, 105, 101, 116, 97, 114,
        121, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 56, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 8, 0, 0, 0, 184, 0, 0, 0, 0,
        0, 0, 0, 1, 0, 0, 0, 9, 0, 0, 0, 159, 235, 1, 0, 24, 0, 0, 0, 0, 0, 0, 0, 240, 2, 0, 0,
        240, 2, 0, 0, 52, 3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 3, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 4,
        0, 0, 0, 32, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 3, 0, 0, 0, 0, 2, 0, 0, 0, 4, 0, 0, 0, 15, 0, 0,
        0, 5, 0, 0, 0, 0, 0, 0, 1, 4, 0, 0, 0, 32, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 6, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 3, 0, 0, 0, 0, 2, 0, 0, 0, 4, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        2, 8, 0, 0, 0, 25, 0, 0, 0, 0, 0, 0, 8, 9, 0, 0, 0, 31, 0, 0, 0, 0, 0, 0, 1, 4, 0, 0, 0,
        32, 0, 0, 0, 0, 0, 0, 0, 4, 0, 0, 4, 32, 0, 0, 0, 44, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 49,
        0, 0, 0, 5, 0, 0, 0, 64, 0, 0, 0, 61, 0, 0, 0, 7, 0, 0, 0, 128, 0, 0, 0, 65, 0, 0, 0, 7, 0,
        0, 0, 192, 0, 0, 0, 71, 0, 0, 0, 0, 0, 0, 14, 10, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        2, 13, 0, 0, 0, 85, 0, 0, 0, 10, 0, 0, 4, 72, 0, 0, 0, 0, 0, 0, 0, 14, 0, 0, 0, 0, 0, 0, 0,
        99, 0, 0, 0, 8, 0, 0, 0, 64, 0, 0, 0, 106, 0, 0, 0, 8, 0, 0, 0, 96, 0, 0, 0, 115, 0, 0, 0,
        8, 0, 0, 0, 128, 0, 0, 0, 126, 0, 0, 0, 19, 0, 0, 0, 160, 0, 0, 0, 137, 0, 0, 0, 20, 0, 0,
        0, 32, 1, 0, 0, 149, 0, 0, 0, 8, 0, 0, 0, 64, 1, 0, 0, 159, 0, 0, 0, 19, 0, 0, 0, 96, 1, 0,
        0, 169, 0, 0, 0, 8, 0, 0, 0, 224, 1, 0, 0, 180, 0, 0, 0, 8, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0,
        0, 2, 0, 0, 5, 8, 0, 0, 0, 0, 0, 0, 0, 15, 0, 0, 0, 0, 0, 0, 0, 196, 0, 0, 0, 17, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 5, 8, 0, 0, 0, 203, 0, 0, 0, 16, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 2, 32, 0, 0, 0, 206, 0, 0, 0, 0, 0, 0, 8, 18, 0, 0, 0, 212, 0, 0, 0, 0,
        0, 0, 1, 8, 0, 0, 0, 64, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3, 0, 0, 0, 0, 8, 0, 0, 0, 4, 0, 0,
        0, 4, 0, 0, 0, 231, 0, 0, 0, 0, 0, 0, 8, 21, 0, 0, 0, 238, 0, 0, 0, 0, 0, 0, 8, 22, 0, 0,
        0, 244, 0, 0, 0, 0, 0, 0, 1, 2, 0, 0, 0, 16, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 13, 2, 0, 0, 0,
        3, 1, 0, 0, 12, 0, 0, 0, 7, 1, 0, 0, 1, 0, 0, 12, 23, 0, 0, 0, 23, 1, 0, 0, 0, 0, 0, 1, 1,
        0, 0, 0, 8, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 3, 0, 0, 0, 0, 25, 0, 0, 0, 4, 0, 0, 0, 12, 0, 0,
        0, 28, 1, 0, 0, 0, 0, 0, 14, 26, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 10, 29, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 9, 30, 0, 0, 0, 36, 1, 0, 0, 0, 0, 0, 8, 8, 0, 0, 0, 40, 1, 0, 0, 0,
        0, 0, 14, 28, 0, 0, 0, 1, 0, 0, 0, 55, 1, 0, 0, 0, 0, 0, 7, 0, 0, 0, 0, 20, 3, 0, 0, 1, 0,
        0, 15, 12, 0, 0, 0, 27, 0, 0, 0, 0, 0, 0, 0, 12, 0, 0, 0, 28, 3, 0, 0, 1, 0, 0, 15, 4, 0,
        0, 0, 31, 0, 0, 0, 0, 0, 0, 0, 4, 0, 0, 0, 36, 3, 0, 0, 1, 0, 0, 15, 32, 0, 0, 0, 11, 0, 0,
        0, 0, 0, 0, 0, 32, 0, 0, 0, 0, 105, 110, 116, 0, 95, 95, 65, 82, 82, 65, 89, 95, 83, 73,
        90, 69, 95, 84, 89, 80, 69, 95, 95, 0, 95, 95, 117, 51, 50, 0, 117, 110, 115, 105, 103,
        110, 101, 100, 32, 105, 110, 116, 0, 116, 121, 112, 101, 0, 109, 97, 120, 95, 101, 110,
        116, 114, 105, 101, 115, 0, 107, 101, 121, 0, 118, 97, 108, 117, 101, 0, 115, 111, 108,
        118, 101, 114, 95, 115, 111, 99, 107, 101, 116, 0, 98, 112, 102, 95, 115, 107, 95, 108,
        111, 111, 107, 117, 112, 0, 102, 97, 109, 105, 108, 121, 0, 112, 114, 111, 116, 111, 99,
        111, 108, 0, 114, 101, 109, 111, 116, 101, 95, 105, 112, 52, 0, 114, 101, 109, 111, 116,
        101, 95, 105, 112, 54, 0, 114, 101, 109, 111, 116, 101, 95, 112, 111, 114, 116, 0, 108,
        111, 99, 97, 108, 95, 105, 112, 52, 0, 108, 111, 99, 97, 108, 95, 105, 112, 54, 0, 108,
        111, 99, 97, 108, 95, 112, 111, 114, 116, 0, 105, 110, 103, 114, 101, 115, 115, 95, 105,
        102, 105, 110, 100, 101, 120, 0, 99, 111, 111, 107, 105, 101, 0, 115, 107, 0, 95, 95, 117,
        54, 52, 0, 117, 110, 115, 105, 103, 110, 101, 100, 32, 108, 111, 110, 103, 32, 108, 111,
        110, 103, 0, 95, 95, 98, 101, 49, 54, 0, 95, 95, 117, 49, 54, 0, 117, 110, 115, 105, 103,
        110, 101, 100, 32, 115, 104, 111, 114, 116, 0, 99, 116, 120, 0, 112, 114, 111, 120, 121,
        95, 99, 104, 97, 108, 108, 101, 110, 103, 101, 0, 99, 104, 97, 114, 0, 76, 73, 67, 69, 78,
        83, 69, 0, 117, 51, 50, 0, 67, 72, 65, 76, 76, 69, 78, 71, 69, 95, 80, 79, 82, 84, 0, 98,
        112, 102, 95, 115, 111, 99, 107, 0, 47, 114, 111, 111, 116, 47, 82, 117, 115, 116, 45, 112,
        114, 111, 106, 101, 99, 116, 115, 47, 99, 101, 114, 116, 111, 110, 97, 117, 116, 47, 115,
        114, 99, 47, 98, 112, 102, 47, 112, 111, 114, 116, 95, 109, 97, 112, 112, 101, 114, 46, 98,
        112, 102, 46, 99, 0, 32, 32, 32, 32, 105, 102, 32, 40, 99, 116, 120, 45, 62, 102, 97, 109,
        105, 108, 121, 32, 33, 61, 32, 65, 70, 95, 73, 78, 69, 84, 32, 38, 38, 32, 99, 116, 120,
        45, 62, 102, 97, 109, 105, 108, 121, 32, 33, 61, 32, 65, 70, 95, 73, 78, 69, 84, 54, 41,
        32, 123, 0, 32, 32, 32, 32, 105, 102, 32, 40, 99, 116, 120, 45, 62, 112, 114, 111, 116,
        111, 99, 111, 108, 32, 33, 61, 32, 73, 80, 80, 82, 79, 84, 79, 95, 84, 67, 80, 32, 124,
        124, 32, 99, 116, 120, 45, 62, 108, 111, 99, 97, 108, 95, 112, 111, 114, 116, 32, 33, 61,
        32, 67, 72, 65, 76, 76, 69, 78, 71, 69, 95, 80, 79, 82, 84, 41, 32, 123, 0, 32, 32, 32, 32,
        105, 102, 32, 40, 99, 116, 120, 45, 62, 102, 97, 109, 105, 108, 121, 32, 61, 61, 32, 65,
        70, 95, 73, 78, 69, 84, 41, 32, 123, 0, 32, 32, 32, 32, 32, 32, 32, 32, 117, 51, 50, 32,
        114, 101, 109, 111, 116, 101, 95, 105, 112, 118, 52, 32, 61, 32, 98, 112, 102, 95, 110,
        116, 111, 104, 108, 40, 99, 116, 120, 45, 62, 114, 101, 109, 111, 116, 101, 95, 105, 112,
        52, 41, 59, 0, 32, 32, 32, 32, 95, 95, 117, 51, 50, 32, 105, 100, 120, 32, 61, 32, 99, 116,
        120, 45, 62, 102, 97, 109, 105, 108, 121, 32, 61, 61, 32, 65, 70, 95, 73, 78, 69, 84, 32,
        63, 32, 48, 32, 58, 32, 49, 59, 0, 32, 32, 32, 32, 115, 107, 32, 61, 32, 98, 112, 102, 95,
        109, 97, 112, 95, 108, 111, 111, 107, 117, 112, 95, 101, 108, 101, 109, 40, 38, 115, 111,
        108, 118, 101, 114, 95, 115, 111, 99, 107, 101, 116, 44, 32, 38, 105, 100, 120, 41, 59, 0,
        32, 32, 32, 32, 105, 102, 32, 40, 33, 115, 107, 41, 0, 32, 32, 32, 32, 98, 112, 102, 95,
        115, 107, 95, 97, 115, 115, 105, 103, 110, 40, 99, 116, 120, 44, 32, 115, 107, 44, 32, 48,
        41, 59, 0, 32, 32, 32, 32, 98, 112, 102, 95, 115, 107, 95, 114, 101, 108, 101, 97, 115,
        101, 40, 115, 107, 41, 59, 0, 125, 0, 48, 58, 49, 0, 48, 58, 50, 0, 48, 58, 56, 0, 48, 58,
        51, 0, 108, 105, 99, 101, 110, 115, 101, 0, 46, 114, 111, 100, 97, 116, 97, 0, 46, 109, 97,
        112, 115, 0, 115, 107, 95, 108, 111, 111, 107, 117, 112, 0, 0, 0, 0, 0, 159, 235, 1, 0, 32,
        0, 0, 0, 0, 0, 0, 0, 20, 0, 0, 0, 20, 0, 0, 0, 76, 1, 0, 0, 96, 1, 0, 0, 124, 0, 0, 0, 8,
        0, 0, 0, 42, 3, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 24, 0, 0, 0, 16, 0, 0, 0, 42, 3, 0, 0, 20, 0,
        0, 0, 0, 0, 0, 0, 64, 1, 0, 0, 120, 1, 0, 0, 14, 152, 0, 0, 8, 0, 0, 0, 64, 1, 0, 0, 120,
        1, 0, 0, 32, 152, 0, 0, 16, 0, 0, 0, 64, 1, 0, 0, 120, 1, 0, 0, 40, 152, 0, 0, 24, 0, 0, 0,
        64, 1, 0, 0, 120, 1, 0, 0, 9, 152, 0, 0, 32, 0, 0, 0, 64, 1, 0, 0, 181, 1, 0, 0, 14, 164,
        0, 0, 40, 0, 0, 0, 64, 1, 0, 0, 181, 1, 0, 0, 38, 164, 0, 0, 48, 0, 0, 0, 64, 1, 0, 0, 181,
        1, 0, 0, 46, 164, 0, 0, 56, 0, 0, 0, 64, 1, 0, 0, 181, 1, 0, 0, 60, 164, 0, 0, 80, 0, 0, 0,
        64, 1, 0, 0, 181, 1, 0, 0, 9, 164, 0, 0, 88, 0, 0, 0, 64, 1, 0, 0, 2, 2, 0, 0, 14, 188, 0,
        0, 96, 0, 0, 0, 64, 1, 0, 0, 2, 2, 0, 0, 9, 188, 0, 0, 104, 0, 0, 0, 64, 1, 0, 0, 36, 2, 0,
        0, 27, 192, 0, 0, 128, 0, 0, 0, 64, 1, 0, 0, 90, 2, 0, 0, 22, 220, 0, 0, 144, 0, 0, 0, 64,
        1, 0, 0, 90, 2, 0, 0, 29, 220, 0, 0, 160, 0, 0, 0, 64, 1, 0, 0, 90, 2, 0, 0, 11, 220, 0, 0,
        184, 0, 0, 0, 64, 1, 0, 0, 138, 2, 0, 0, 10, 224, 0, 0, 208, 0, 0, 0, 64, 1, 0, 0, 190, 2,
        0, 0, 9, 228, 0, 0, 216, 0, 0, 0, 64, 1, 0, 0, 203, 2, 0, 0, 5, 236, 0, 0, 0, 1, 0, 0, 64,
        1, 0, 0, 234, 2, 0, 0, 5, 240, 0, 0, 16, 1, 0, 0, 64, 1, 0, 0, 2, 3, 0, 0, 1, 248, 0, 0,
        16, 0, 0, 0, 42, 3, 0, 0, 7, 0, 0, 0, 0, 0, 0, 0, 13, 0, 0, 0, 4, 3, 0, 0, 0, 0, 0, 0, 16,
        0, 0, 0, 13, 0, 0, 0, 4, 3, 0, 0, 0, 0, 0, 0, 32, 0, 0, 0, 13, 0, 0, 0, 8, 3, 0, 0, 0, 0,
        0, 0, 48, 0, 0, 0, 13, 0, 0, 0, 12, 3, 0, 0, 0, 0, 0, 0, 88, 0, 0, 0, 13, 0, 0, 0, 4, 3, 0,
        0, 0, 0, 0, 0, 104, 0, 0, 0, 13, 0, 0, 0, 16, 3, 0, 0, 0, 0, 0, 0, 128, 0, 0, 0, 13, 0, 0,
        0, 4, 3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 3, 0, 0, 0, 32, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 64, 0, 0, 0, 0, 0, 0, 0, 177, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 9, 0, 0, 0, 2, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 248, 0, 0, 0, 0, 0, 0, 0, 8, 1, 0, 0, 0, 0,
        0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 8, 0, 0, 0, 0, 0, 0, 0, 24, 0, 0, 0, 0, 0, 0, 0, 17, 0, 0, 0,
        1, 0, 0, 0, 6, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 32, 1,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 8, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        27, 0, 0, 0, 1, 0, 0, 0, 3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 32, 3, 0, 0, 0, 0,
        0, 0, 12, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 35, 0, 0, 0, 1, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 44, 3,
        0, 0, 0, 0, 0, 0, 4, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 4, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 43, 0, 0, 0, 1, 0, 0, 0, 3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 48, 3, 0, 0, 0, 0, 0, 0, 32, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 8, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 149, 0, 0, 0, 9, 0, 0, 0, 64, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 80, 3, 0, 0, 0, 0, 0, 0, 32, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 3, 0, 0,
        0, 8, 0, 0, 0, 0, 0, 0, 0, 16, 0, 0, 0, 0, 0, 0, 0, 163, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 112, 3, 0, 0, 0, 0, 0, 0, 60, 6, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 8, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 168, 0, 0, 0, 1, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 176, 9, 0, 0, 0, 0, 0, 0, 252, 1, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 8, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    ];
}
